import { z } from 'zod';
import { Actor, AppError } from './auth';
import { auditStatement, db, one, statement } from '@/db/queries';
import type { PersonalFinanceConfig } from './personal-finance-model';

const defaults: PersonalFinanceConfig = {
  availableMinor: 2_500_000_000,
  reserveMinor: 100_000_000,
  personalIncomeMinor: 330_164_229,
  livingCostsMinor: 344_000_000,
  businessIncomeMinor: 0,
  businessFixedCostsMinor: 51_000_000,
  businessExtraordinaryMinor: 10_000_000,
  businessContributionMarginBps: 4000,
  debts: [
    [
      'bancor-1',
      'Bancor',
      'Préstamo personal 1',
      'loan',
      37_163_537,
      null,
      null,
      null,
      17,
      36,
      null,
      null,
      'medium',
      'Solicitar saldo de cancelación anticipada',
      'review',
      'pending',
      'Falta cuota mensual exacta.',
    ],
    [
      'bancor-2',
      'Bancor',
      'Préstamo personal 2',
      'loan',
      461_446_864,
      null,
      35_961_480,
      null,
      38,
      60,
      null,
      '2026-10-01',
      'medium',
      'Mantener y comparar cancelación',
      'pending',
      'confirmed',
      'Sistema francés.',
    ],
    [
      'credicuotas',
      'Credicuotas',
      'Préstamo personal',
      'loan',
      330_263_500,
      330_263_500,
      45_747_200,
      null,
      14,
      18,
      null,
      null,
      'high',
      'Candidata a cancelación por flujo liberado',
      'review',
      'confirmed',
      'Cancelar libera $457.472 por mes.',
    ],
    [
      'credicuotas-linea',
      'Credicuotas',
      'Línea de crédito',
      'credit',
      14_786_900,
      14_786_900,
      null,
      null,
      null,
      null,
      null,
      null,
      'medium',
      'Confirmar vencimiento y condiciones',
      'review',
      'pending',
      'Total informado; faltan cuota y tasa.',
    ],
    [
      'brubank-1',
      'Brubank',
      'Préstamo 1',
      'loan',
      21_429_568,
      21_429_568,
      21_429_568,
      null,
      1,
      3,
      null,
      null,
      'maintain',
      'Pagar última cuota',
      'pending',
      'confirmed',
      'Queda una cuota.',
    ],
    [
      'brubank-2',
      'Brubank',
      'Préstamo 2',
      'loan',
      82_438_268,
      null,
      20_428_000,
      null,
      4,
      6,
      null,
      null,
      'maintain',
      'Cerca de finalizar',
      'pending',
      'estimated',
      'Cuotas siguientes aproximadas.',
    ],
    [
      'brubank-3',
      'Brubank',
      'Préstamo 3',
      'loan',
      63_556_300,
      null,
      15_889_075,
      null,
      4,
      6,
      null,
      null,
      'maintain',
      'Mantener cuotas',
      'pending',
      'confirmed',
      'Cuatro cuotas pendientes.',
    ],
    [
      'uala',
      'Ualá',
      'Préstamo personal',
      'loan',
      391_538_442,
      413_889_602,
      35_158_830,
      null,
      31,
      48,
      null,
      null,
      'medium',
      'Comparar con Credicuotas antes de cancelar',
      'review',
      'confirmed',
      'Cancelación anticipada informada.',
    ],
    [
      'mp-1',
      'Mercado Pago',
      'Crédito 1',
      'credit',
      40_201_569,
      40_201_569,
      14_313_047,
      null,
      3,
      3,
      null,
      null,
      'low',
      'Evaluar esperar por pocas cuotas',
      'pending',
      'confirmed',
      'Tres importes pendientes.',
    ],
    [
      'mp-2',
      'Mercado Pago',
      'Crédito 2',
      'credit',
      63_602_130,
      63_602_130,
      23_293_344,
      null,
      3,
      3,
      null,
      null,
      'low',
      'Evaluar esperar por pocas cuotas',
      'pending',
      'confirmed',
      'Tres importes pendientes.',
    ],
    [
      'mp-3',
      'Mercado Pago',
      'Crédito 3',
      'credit',
      42_020_110,
      42_020_110,
      15_389_248,
      null,
      3,
      3,
      null,
      null,
      'low',
      'Evaluar esperar por pocas cuotas',
      'pending',
      'confirmed',
      'Tres importes pendientes.',
    ],
    [
      'moni',
      'Moni',
      'Préstamo',
      'loan',
      363_329_522,
      null,
      38_464_724,
      null,
      10,
      10,
      null,
      null,
      'high',
      'Confirmar cuotas pendientes',
      'review',
      'estimated',
      'Revisar cantidad exacta de cuotas pendientes.',
    ],
    [
      'cordobesa',
      'Bancor',
      'Cordobesa Mastercard',
      'card',
      1_528_774_101,
      1_528_774_101,
      null,
      264_353_400,
      null,
      null,
      10827,
      null,
      'urgent',
      'Evaluar cancelar saldo total',
      'review',
      'confirmed',
      'Saldo financiado con CFT TEA 108,273%.',
    ],
    [
      'naranja',
      'Naranja X',
      'Tarjeta Naranja X',
      'card',
      75_147_452,
      75_147_452,
      null,
      null,
      null,
      null,
      null,
      null,
      'medium',
      'Actualizar saldo en pesos y USD',
      'review',
      'confirmed',
      'Incluye USD 5,82 pendiente de conversión.',
    ],
    [
      'galicia-visa',
      'Galicia',
      'Visa',
      'card',
      94_326_387,
      94_326_387,
      null,
      18_080_000,
      null,
      null,
      15959,
      null,
      'urgent',
      'Evitar refinanciación y revisar pago total',
      'review',
      'confirmed',
      'CFT TEA 159,59% y punitorios.',
    ],
    [
      'galicia-master',
      'Galicia',
      'Mastercard',
      'card',
      150_178_655,
      150_178_655,
      null,
      18_384_000,
      null,
      null,
      14458,
      null,
      'urgent',
      'Actualizar resumen antes de decidir',
      'review',
      'pending',
      'REQUIERE ACTUALIZAR RESUMEN.',
    ],
  ].map((d: any[]) => ({
    id: d[0],
    entity: d[1],
    label: d[2],
    kind: d[3],
    scope: 'personal',
    balanceMinor: d[4],
    payoffMinor: d[5],
    monthlyMinor: d[6],
    minimumMinor: d[7],
    remainingInstallments: d[8],
    totalInstallments: d[9],
    annualRateBps: d[10],
    nextDueOn: d[11],
    priority: d[12],
    decision: d[13],
    status: d[14],
    quality: d[15],
    notes: d[16],
  })),
  payments: [],
};

const money = z.number().int().min(0).max(100_000_000_000);
const debtSchema = z
  .object({
    id: z.string().min(1).max(80),
    entity: z.string().min(1).max(100),
    label: z.string().min(1).max(140),
    kind: z.enum(['card', 'loan', 'credit']),
    scope: z.enum(['personal', 'business']),
    balanceMinor: money,
    payoffMinor: money.nullable(),
    monthlyMinor: money.nullable(),
    minimumMinor: money.nullable(),
    remainingInstallments: z.number().int().min(0).max(600).nullable(),
    totalInstallments: z.number().int().min(1).max(600).nullable(),
    annualRateBps: z.number().int().min(0).max(100000).nullable(),
    nextDueOn: z.iso.date().nullable(),
    priority: z.enum(['urgent', 'high', 'medium', 'low', 'maintain']),
    decision: z.string().max(500),
    status: z.enum(['pending', 'review', 'scheduled', 'paid', 'closed']),
    quality: z.enum(['confirmed', 'estimated', 'pending']),
    notes: z.string().max(1000),
  })
  .strict();
const paymentSchema = z
  .object({
    id: z.string().min(1).max(100),
    debtId: z.string().min(1).max(80),
    paidOn: z.iso.datetime(),
    amountMinor: money,
    mode: z.enum(['minimum', 'installment', 'advance', 'custom', 'total']),
    installmentCount: z.number().int().min(1).max(600).nullable(),
  })
  .strict();
const configSchema = z
  .object({
    availableMinor: money,
    reserveMinor: money,
    personalIncomeMinor: money,
    livingCostsMinor: money,
    businessIncomeMinor: money,
    businessFixedCostsMinor: money,
    businessExtraordinaryMinor: money,
    businessContributionMarginBps: z
      .number()
      .int()
      .min(0)
      .max(10000)
      .default(4000),
    debts: z.array(debtSchema).max(100),
    payments: z.array(paymentSchema).max(5000).default([]),
  })
  .strict();

function requireOwner(actor: Actor) {
  if (actor.role !== 'ADMIN') throw new AppError(403, 'Acceso denegado.');
}

export async function getPersonalFinance(actor: Actor) {
  requireOwner(actor);
  const stored = await one<{ value: string }>(
    'SELECT value FROM settings WHERE key=?',
    'personal-finance',
  );
  if (!stored) return defaults;
  try {
    return configSchema.parse(JSON.parse(stored.value));
  } catch {
    throw new AppError(
      500,
      'La configuración financiera personal debe revisarse.',
    );
  }
}

export async function savePersonalFinance(actor: Actor, raw: unknown) {
  requireOwner(actor);
  const input = configSchema.parse(raw);
  const before = await one<{ value: string }>(
    'SELECT value FROM settings WHERE key=?',
    'personal-finance',
  );
  await db().batch([
    statement(
      `INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`,
      'personal-finance',
      JSON.stringify(input),
    ),
    auditStatement(
      actor.id,
      'Actualizar centro financiero personal',
      'personal-finance',
      before ? { configured: true } : null,
      {
        configured: true,
        debts: input.debts.length,
        payments: input.payments.length,
        contributionMarginBps: input.businessContributionMarginBps,
      },
    ),
  ]);
  return input;
}
